services:
  api_gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    env_file:
      - .env
      - ./gateway/.env
    depends_on:
      - user_sys
      - product_sys
    ports:
      - '${GATEWAY_PORT}:3000'
    networks:
      - mec_network

networks:
  mec_network:
    driver: bridge
    ipam:
      driver: default
